### ISSUE TITLE
series_premiere BUG

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#888] opened 2016-02-26 21:17 UTC
```
2016-02-26 22:06 VERBOSE  series        premieren_de    Found different quality for American.Horror.Story.S05E12.Seien.Sie.unser.Gast.German.DD51.Dubbed.DL.720p.iTunesHD.AVC-TVS. Was 720p dd5.1, overriding with 720p.
2016-02-26 22:06 CRITICAL task          premieren_de    BUG: Unhandled error in plugin series_premiere: Series flagged invalid
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\filter\series_premiere.py", line 62, in on_task_metainfo
    if guess_entry(entry, allow_seasonless=allow_seasonless, config=group_settings):
  File "c:\python27\lib\site-packages\flexget\plugins\metainfo\series.py", line 46, in guess_entry
    populate_entry_fields(entry, parsed, config)
  File "c:\python27\lib\site-packages\flexget\plugins\filter\series.py", line 856, in populate_entry_fields
    entry['series_id'] = parser.pack_identifier
  File "c:\python27\lib\site-packages\flexget\plugins\parsers\parser_common.py", line 548, in pack_identifier
    return self.identifier
  File "c:\python27\lib\site-packages\flexget\plugins\parsers\parser_common.py", line 539, in identifier
    return self.identifiers[0]
  File "c:\python27\lib\site-packages\flexget\plugins\parsers\parser_common.py", line 524, in identifiers
    raise Exception('Series flagged invalid')
Exception: Series flagged invalid

```

**Comment by crack00r** [comment] 2016-03-09 06:17
latest Version still have this error . . 


```
2016-03-08 23:26 VERBOSE  series        premieren_en    Found different quality for Major.Crimes.S04E01.24.Rosen.German.DD51.Dubbed.DL.1080p.iTunesHD.AVC-TVS. Was 1080p dd5.1, overriding with 1080p.
2016-03-08 23:26 CRITICAL task          premieren_en    BUG: Unhandled error in plugin series_premiere: Series flagged invalid
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\filter\series_premiere.py", line 62, in on_task_metainfo
    if guess_entry(entry, allow_seasonless=allow_seasonless, config=group_settings):
  File "c:\python27\lib\site-packages\flexget\plugins\metainfo\series.py", line 46, in guess_entry
    populate_entry_fields(entry, parsed, config)
  File "c:\python27\lib\site-packages\flexget\plugins\filter\series.py", line 870, in populate_entry_fields
    entry['series_id'] = parser.pack_identifier
  File "c:\python27\lib\site-packages\flexget\plugins\parsers\parser_common.py", line 548, in pack_identifier
    return self.identifier
  File "c:\python27\lib\site-packages\flexget\plugins\parsers\parser_common.py", line 539, in identifier
    return self.identifiers[0]
  File "c:\python27\lib\site-packages\flexget\plugins\parsers\parser_common.py", line 524, in identifiers
    raise Exception('Series flagged invalid')
Exception: Series flagged invalid

```

**Comment by crawln45** [comment] 2016-04-27 05:23
Are either of you using Guessit parser?

**Comment by cvium** [comment] 2016-08-08 14:16
seems like a duplicate of #735

**Closed by cvium** 2016-08-08 14:16 UTC
