### ISSUE TITLE
Can't start flexget in Asuswrt

### ISSUE THREAD

**Issue by mundodisco8** [Flexget/Flexget#1282] opened 2016-07-18 15:46 UTC
I've been running flexget successfully for a while in my Asus AC-RT56U router for a while (v1.X). The router is running Merlin's version of the firmware. After setting it up on a Raspberry pi, I found out the new website and the updated 2.X version of flexget, and decided to update the version running on my router. Since the update (done with pip install --upgrade flexget), I haven't been able to run it, as it crashes with an error related to lib2to3.

### Expected behaviour:
Running flexget -v would show the installed version

### Actual behaviour:
Flexget crashes with the following error

```
Traceback (most recent call last):
  File "/opt/bin/flexget", line 7, in <module>
    from flexget import main
  File "/opt/lib/python2.7/site-packages/flexget/__init__.py", line 11, in <module>
    from flexget import logger
  File "/opt/lib/python2.7/site-packages/flexget/logger.py", line 20, in <module>
    from flexget.utils.tools import io_encoding
  File "/opt/lib/python2.7/site-packages/flexget/utils/tools.py", line 5, in <module>
    from past.builtins import basestring
  File "/opt/lib/python2.7/site-packages/past/__init__.py", line 88, in <module>
    from past.translation import install_hooks as autotranslate
  File "/opt/lib/python2.7/site-packages/past/translation/__init__.py", line 41, in <module>
    from lib2to3.pgen2.parse import ParseError
ImportError: No module named lib2to3.pgen2.parse
```

### Steps to reproduce:
Install flexget following the instructions on the wiki (soma packages failed, is it because wiki needs update or because they are not available in entware for Merlin's AsusWRT?)

Run flexget

The program has been working before, with one of the 1.X versions, but I updated to the latest version and I haven't been able to run it.

#### Config:  
Nothing out of the ordinary

#### Log:
Can't generate a log, flexget refuses to run

### Additional information:

- Flexget Version: 2.1.15
- Python Version: 2.7.11
- Installation method: pip install, as per the wiki.
- OS and version: Merlin's AsusWRT 380.59
- Link to crash log: Can't generate log

If some info is missing, please tell me and I will update the issue.

**Comment by cvium** [comment] 2016-07-18 15:49
Duplicate of #1093

**Closed by cvium** 2016-07-18 15:49 UTC
