### ISSUE TITLE
imdb languages not being found again

### ISSUE THREAD

**Issue by dchubkov** [Flexget/Flexget#1447] opened 2016-10-15 13:05 UTC
### Expected behaviour:

the languages from the imdb page should be extracted and available in the entries dict
### Actual behaviour:

no languages are found on the page and the languages field is empty
### Steps to reproduce:

flexget -c /data/Settings/FlexGet/config.yml --test inject "Chongqing Hot Pot (2016)" "http://rutor.is/torrent/528738" --tasks rutor_new_high_rated_hd_movies --now --debug --dump eval
#### Log:

```
title            : Chongqing Hot Pot
url              : http://rutor.is/torrent/528738
original_url     : http://rutor.is/torrent/528738
imdb_actors      : {u'nm1179512': u'Kun Chen', u'nm2290954': u'Hao Qin', u'nm3419887': u'Baihe Bai'}
imdb_directors   : {u'nm3619844': u'Qing Yang'}
imdb_genres      : [thriller]
imdb_id          : tt5596352
imdb_languages   : []
imdb_mpaa_rating : 
imdb_name        : Chongqing Hot Pot
imdb_original_name: None
imdb_photo       : https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ2ODY0NzYzOF5BMl5BanBnXkFtZTgwMDUwODI1ODE@._V1_UX182_CR0,0,182,268_AL_.jpg
imdb_plot_outline: When a young man and his friends dig a hole to expand their restaurant, they enter a nearby bank vault that is being robbed.
imdb_score       : 6.7
imdb_url         : http://www.imdb.com/title/tt5596352/
imdb_votes       : 507
imdb_year        : 2016
movie_name       : Chongqing Hot Pot
movie_year       : 2016
quality          : unknown
task             : rutor_new_high_rated_hd_movies
```
### Additional information:
- Flexget Version: 2.3.44
- Python Version: 2.7.6
- Installation method: sudo pip install --upgrade flexget
- OS and version: Ubuntu 14.04.1

This is broken again after fixing of https://github.com/Flexget/Flexget/issues/1413

**Comment by cvium** [comment] 2016-10-15 13:14
Works for me

```
-- Undecided: --------------------------
title            : Chongqing Hot Pot (2016)
url              : mock://localhost/mock/-1986194858
original_url     : mock://localhost/mock/-1986194858
imdb_actors      : {u'nm1179512': u'Kun Chen', u'nm2290954': u'Hao Qin', u'nm3419887': u'Baihe Bai'}
imdb_directors   : {u'nm3619844': u'Qing Yang'}
imdb_genres      : [thriller]
imdb_id          : tt5596352
imdb_languages   : [mandarin]
imdb_mpaa_rating : 
imdb_name        : Chongqing Hot Pot
imdb_original_name: None
imdb_photo       : https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ2ODY0NzYzOF5BMl5BanBnXkFtZTgwMDUwODI1ODE@._V1_UX182_CR0,0,182,268_AL_.jpg
imdb_plot_outline: When a young man and his friends dig a hole to expand their restaurant, they enter a nearby bank vault that is being robbed.
imdb_score       : 6.7
imdb_url         : http://www.imdb.com/title/tt5596352/
imdb_votes       : 513
imdb_year        : 2016
movie_name       : Chongqing Hot Pot
movie_year       : 2016
quality          : unknown
task             : test_imdb
```

**Comment by dchubkov** [comment] 2016-10-15 14:48
@cvium works on same environment and Flexget version?

**Comment by cvium** [comment] 2016-10-15 15:21
Latest Flexget version. Python 2.7.11.

**Comment by dchubkov** [comment] 2016-10-15 20:59
So what's the problem might be on my side? How to found out the root cause?

**Comment by liiight** [comment] 2016-10-15 21:03
maybe `Accept-Language` header? do you get those fields via browser?

**Comment by dchubkov** [comment] 2016-10-15 21:10
how to check it via browser? on imdb site for this movie I can see languages section

**Comment by cvium** [comment] 2016-10-15 21:10
We need your config.

**Comment by dchubkov** [comment] 2016-10-15 21:22
it quite big
https://www.dropbox.com/s/dmi3tnwdllkmco0/config.yml?dl=0

**Comment by cvium** [comment] 2016-10-18 20:03
I can't reproduce the issue.

**Comment by cvium** [comment] 2016-11-11 08:08
Closing this as I can't reproduce it. Maybe it was a caching issue.

**Closed by cvium** 2016-11-11 08:08 UTC
Labels: Works for me
