### ISSUE TITLE
Trakt to sonarr - Sonarr returned an error. Profile does not exist: ProfileId '1'

### ISSUE THREAD

**Issue by Nottin4u** [Flexget/Flexget#2415] opened 2019-06-13 12:46 UTC
### Expected behaviour:

Via my list on trakt.tv - SonarrList, I was trying to add the show "Homestead Rescue" back into my Sonarr, just to verify that it works. Then I would switch over to my general series list.

### Actual behaviour:
it crashes to due to not being able to retrieve the Profile ID from Sonarr to set the wanted values for quality of show, when adding to Sonarr. Looks like the "sonar_list.py" is not receiving a correct JSON response or that it is using the RAW output from Sonarr, without the index available.

### Steps to reproduce:
1. Login to trakt.tv - user profile
2. create a new list "SonarList," and set the visibility to friends
3. verify that flexget have access to the list via:
 flexget trakt auth account
4. run:
flexget execute

#### Config:
```
# secrets: secrets.yml
variables: secrets.yml

tasks:
  fill_sonar:
    trakt_list:
      username: '{? trakttv.username ?}'
      account: '{? trakttv.account ?}'
      list: SonarList
      type: shows
    accept_all: yes
    list_add:
      - sonarr_list:
          base_url: '{? sonarr.url ?}'
          port: '{? sonarr.port ?}'
          base_path: / #added to avoid crash, maybe not needed with dockerinstallation.
          api_key: '{? sonarr.apikey ?}'
          season_folder: true
          ignore_episodes_with_files: true
          ignore_episodes_without_files: true
          search_missing_episodes: false
          series_type: standard
          include_data: false
          profile_id: 2
```
  I'm trying to have the "trakt-to-sonarr" configuration to fill my sonarr installation with new series from Trakt.tv.

#### Log:
<details>
 <summary>(click to expand)</summary>

```
2019-06-13 14:03 VERBOSE  details       fill_sonar      Summary - Accepted: 93 (Rejected: 0 Undecided: 0 Failed: 0)
2019-06-13 14:03 VERBOSE  list_add      fill_sonar      adding accepted entries into sonarr_list - {u'include_ended': True, u'monitored': True, u'tags': [0], u'series_type': u'standard', u'profile_id': 2, u'ignore_episodes_with_files': True, u'base_url': u'http://XXX.XXX.X.XX', u'base_path': u'/', u'ignore_episodes_without_files': True, u'only_monitored': True, u'include_data': False, u'search_missing_episodes': False, u'api_key': u'_REDACTED__APIKEY', u'port': 8989, u'season_folder': True}
2019-06-13 14:03 CRITICAL plugin        fill_sonar      Sonarr returned an error. Profile does not exist: ProfileId '2'
2019-06-13 14:03 WARNING  task          fill_sonar      Aborting task (plugin: list_add)
2019-06-13 14:03 INFO     performance                   Performance results for task fill_sonar:
2019-06-13 14:03 INFO     performance                   seen            took 0.14 sec (93 queries)
2019-06-13 14:03 INFO     performance                   retry_failed    took 0.10 sec (93 queries)
2019-06-13 14:03 INFO     performance                   list_add        took 3.82 sec (0 queries)
2019-06-13 14:03 INFO     performance                   backlog         took 0.22 sec (188 queries)
2019-06-13 14:15 CRITICAL plugin        fill_sonar      Sonarr returned an error. Profile does not exist: ProfileId '2'
2019-06-13 14:15 WARNING  task          fill_sonar      Aborting task (plugin: list_add)

```
</details>

### Additional information:

- FlexGet version: 2.21.8
- Python version: Python 2.7.12
- Installation method: PIP
- Using daemon (yes/no): No
- OS and version: "Linux SB 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:23:40 UTC 2018 i686 i686 i686 GNU/Linux"
- Link to crash log: None

- Sonarr version: Sonarr Ver. 2.0.0.5322
- installed on docker (on synology)

**Comment by liiight** [comment] 2019-06-13 12:57
did you deliberately set `profile_id: 2` in your config?

**Comment by Nottin4u** [comment] 2019-06-13 12:58
yes, I have created a new profile to make sure I was using having more than 0, which it by the way not can use due to the restriction says it must be greater than 0.

**Comment by liiight** [comment] 2019-06-13 14:07
Can you run again with debug logs please?

**Comment by Nottin4u** [comment] 2019-06-13 14:17
[debug.txt](https://github.com/Flexget/Flexget/files/3286579/debug.txt)

Here you go: flexget --debug execute > debug.txt

**Comment by Nottin4u** [comment] 2019-06-18 06:30
There might be some information regarding this issue here:
[https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwionIe_svLiAhXtQEEAHeDQAWkQFjAAegQIBRAB&url=https%3A%2F%2Fgithub.com%2Ftidusjar%2FOmbi%2Fissues%2F340&usg=AOvVaw1X-JmniJYWgaG3_KPQMT2c](url)

**Comment by JourneyOver** [comment] 2019-07-02 09:50
@Nottin4u 	can you go to `http://url:port/api/profile?apikey=APIKEY` replace `url:port` with your `url:port` and `APIKEY` with your APIKEY, and post up what is returned.

**Comment by Nottin4u** [comment] 2019-07-02 10:51
This is what is returned without the .txt extension.

[profile.json.txt](https://github.com/Flexget/Flexget/files/3349665/profile.json.txt)

Pushed the save button - and renamed the extension to .txt to upload here.

**Comment by JourneyOver** [comment] 2019-07-02 11:16
Okay I think I see where you messed up. We need to find a way to make it a bit clearer on the wiki page for this option.

Okay here is your profile.json as an example on what ID you should be using:
Full Json:
```Json
[
  {
    "name": "HD-720p",
    "cutoff": {
      "id": 5,
      "name": "WEBDL-720p",
      "source": "web",
      "resolution": 720
    },
    "items": [
      {
        "quality": {
          "id": 0,
          "name": "Unknown",
          "source": "unknown",
          "resolution": 0
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 1,
          "name": "SDTV",
          "source": "television",
          "resolution": 480
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 8,
          "name": "WEBDL-480p",
          "source": "web",
          "resolution": 480
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 2,
          "name": "DVD",
          "source": "dvd",
          "resolution": 480
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 4,
          "name": "HDTV-720p",
          "source": "television",
          "resolution": 720
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 9,
          "name": "HDTV-1080p",
          "source": "television",
          "resolution": 1080
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 10,
          "name": "Raw-HD",
          "source": "televisionRaw",
          "resolution": 1080
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 5,
          "name": "WEBDL-720p",
          "source": "web",
          "resolution": 720
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 6,
          "name": "Bluray-720p",
          "source": "bluray",
          "resolution": 720
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 3,
          "name": "WEBDL-1080p",
          "source": "web",
          "resolution": 1080
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 7,
          "name": "Bluray-1080p",
          "source": "bluray",
          "resolution": 1080
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 16,
          "name": "HDTV-2160p",
          "source": "television",
          "resolution": 2160
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 18,
          "name": "WEBDL-2160p",
          "source": "web",
          "resolution": 2160
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 19,
          "name": "Bluray-2160p",
          "source": "bluray",
          "resolution": 2160
        },
        "allowed": false
      }
    ],
    "language": "english",
    "id": 3
  },
  {
    "name": "HD - 720p/1080p",
    "cutoff": {
      "id": 3,
      "name": "WEBDL-1080p",
      "source": "web",
      "resolution": 1080
    },
    "items": [
      {
        "quality": {
          "id": 0,
          "name": "Unknown",
          "source": "unknown",
          "resolution": 0
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 1,
          "name": "SDTV",
          "source": "television",
          "resolution": 480
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 8,
          "name": "WEBDL-480p",
          "source": "web",
          "resolution": 480
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 2,
          "name": "DVD",
          "source": "dvd",
          "resolution": 480
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 4,
          "name": "HDTV-720p",
          "source": "television",
          "resolution": 720
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 9,
          "name": "HDTV-1080p",
          "source": "television",
          "resolution": 1080
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 10,
          "name": "Raw-HD",
          "source": "televisionRaw",
          "resolution": 1080
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 5,
          "name": "WEBDL-720p",
          "source": "web",
          "resolution": 720
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 6,
          "name": "Bluray-720p",
          "source": "bluray",
          "resolution": 720
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 3,
          "name": "WEBDL-1080p",
          "source": "web",
          "resolution": 1080
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 7,
          "name": "Bluray-1080p",
          "source": "bluray",
          "resolution": 1080
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 16,
          "name": "HDTV-2160p",
          "source": "television",
          "resolution": 2160
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 18,
          "name": "WEBDL-2160p",
          "source": "web",
          "resolution": 2160
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 19,
          "name": "Bluray-2160p",
          "source": "bluray",
          "resolution": 2160
        },
        "allowed": false
      }
    ],
    "language": "english",
    "id": 6
  },
  {
    "name": "test",
    "cutoff": {
      "id": 3,
      "name": "WEBDL-1080p",
      "source": "web",
      "resolution": 1080
    },
    "items": [
      {
        "quality": {
          "id": 0,
          "name": "Unknown",
          "source": "unknown",
          "resolution": 0
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 1,
          "name": "SDTV",
          "source": "television",
          "resolution": 480
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 8,
          "name": "WEBDL-480p",
          "source": "web",
          "resolution": 480
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 2,
          "name": "DVD",
          "source": "dvd",
          "resolution": 480
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 4,
          "name": "HDTV-720p",
          "source": "television",
          "resolution": 720
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 9,
          "name": "HDTV-1080p",
          "source": "television",
          "resolution": 1080
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 10,
          "name": "Raw-HD",
          "source": "televisionRaw",
          "resolution": 1080
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 5,
          "name": "WEBDL-720p",
          "source": "web",
          "resolution": 720
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 6,
          "name": "Bluray-720p",
          "source": "bluray",
          "resolution": 720
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 3,
          "name": "WEBDL-1080p",
          "source": "web",
          "resolution": 1080
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 7,
          "name": "Bluray-1080p",
          "source": "bluray",
          "resolution": 1080
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 16,
          "name": "HDTV-2160p",
          "source": "television",
          "resolution": 2160
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 18,
          "name": "WEBDL-2160p",
          "source": "web",
          "resolution": 2160
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 19,
          "name": "Bluray-2160p",
          "source": "bluray",
          "resolution": 2160
        },
        "allowed": false
      }
    ],
    "language": "english",
    "id": 7
  }
]
```

Take your HD-720p profile as an example. its full profile is:
```Json
{
    "name": "HD-720p",
    "cutoff": {
      "id": 5,
      "name": "WEBDL-720p",
      "source": "web",
      "resolution": 720
    },
    "items": [
      {
        "quality": {
          "id": 0,
          "name": "Unknown",
          "source": "unknown",
          "resolution": 0
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 1,
          "name": "SDTV",
          "source": "television",
          "resolution": 480
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 8,
          "name": "WEBDL-480p",
          "source": "web",
          "resolution": 480
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 2,
          "name": "DVD",
          "source": "dvd",
          "resolution": 480
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 4,
          "name": "HDTV-720p",
          "source": "television",
          "resolution": 720
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 9,
          "name": "HDTV-1080p",
          "source": "television",
          "resolution": 1080
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 10,
          "name": "Raw-HD",
          "source": "televisionRaw",
          "resolution": 1080
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 5,
          "name": "WEBDL-720p",
          "source": "web",
          "resolution": 720
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 6,
          "name": "Bluray-720p",
          "source": "bluray",
          "resolution": 720
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 3,
          "name": "WEBDL-1080p",
          "source": "web",
          "resolution": 1080
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 7,
          "name": "Bluray-1080p",
          "source": "bluray",
          "resolution": 1080
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 16,
          "name": "HDTV-2160p",
          "source": "television",
          "resolution": 2160
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 18,
          "name": "WEBDL-2160p",
          "source": "web",
          "resolution": 2160
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 19,
          "name": "Bluray-2160p",
          "source": "bluray",
          "resolution": 2160
        },
        "allowed": false
      }
    ],
    "language": "english",
    "id": 3
  }
```

Now you may see a bunch of ID in that list, but you see the one at the very bottom below the `"language": "english",` that is the `ID` you would want to use so it would be an ID of `3`. so for your second profile `HD - 720p/1080p` it would be an ID of `6` and then for your `test` profile it would be an ID of `7`

Yes this is all confusing because of one thing sonarr doesn't do, and I wish they would as it'd make things a little nicer, but when you delete a profile from your list it doesn't actually free up the ID that it was using at all. so if you was to delete all default profiles, and then create a new one that new one wouldn't have an ID of `1` it would end up sadly having an ID of whatever number it should be after the default amount of profiles (I can't remember how many default profiles there are anymore)

it's the same thing with tags as well if you where to venture into that option, albeit since you don't start with any tags by default on sonarr, the first tag you create will have an ID of `1` but say you delete it and create a new tag, that new tag would have an ID of `2` 

@Nottin4u

**Comment by JourneyOver** [comment] 2019-07-02 11:23
@liiight 	we need a way to convey the above message in a short enough way to not confuse people on the wiki page otherwise things like this issue may pop up again in the future xD as it's actually user error, and not a bug on neither flexget nor sonarrs side of things.

**Comment by Nottin4u** [comment] 2019-07-02 11:29
well that makes sense, but I will test it at once to verify :) 

thank you, for the explanation. @JourneyOver

**Comment by Nottin4u** [comment] 2019-07-02 11:31
yes!! now it works as specified. thank you! @JourneyOver @liiight 

but we need the wiki updated. :)

**Comment by JourneyOver** [comment] 2019-07-02 11:35
hehe it's not a problem at all @Nottin4u 	^^ I'm actually the one who added a bunch of options to the trakt to sonarr plugin a while back since it was kinda bare at the time when I started using it, so I kinda know the ins and outs of the script a bit on how the options work and all that :P I just wish sonarrs side of things to do with ID's was a bit cleaner (like actually freeing up the ID's of deleted stuff).

**Comment by Nottin4u** [comment] 2019-07-02 12:08
I am now filling my list with new shows in the SonarList and it looks like it is working as expected ^^

so again a big Thank You from me. I hope you will be able to update the Wiki for others :-) 

but yes the Sonarr group should update to make sense of the ID handling overall, but we can probably not expect them to do so.. ;-) 

@JourneyOver @liiight should I close the issue or will you do that?

**Comment by JourneyOver** [comment] 2019-07-02 20:35
You can probably go ahead and close it, I myself don't have the powers to close anything here since I am not part of the team xD I just thought I'd end up chirping in when I came here to see about any recent updates and decided to take a look at issues.

**Closed** 2019-07-03 10:31 UTC
Labels: Bug
