### ISSUE TITLE
[tvmaze] IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed

### ISSUE THREAD

**Issue by DigitalConceptions** [Flexget/Flexget#725] opened 2015-12-19 04:47 UTC
@Flexget/tvmaze

```
# flexget -V
1.2.412.dev
Latest release: 1.2.411
```

I am getting the following errors that seems to be tvmaze DB related... 
I have attached the full log if needed as well: [flexget-2015-12-18-2329.txt](https://github.com/Flexget/Flexget/files/67362/flexget-2015-12-18-2329.txt)

```
2015-12-18 23:29 DEBUG    api_tvmaze    Series-Premieres returning search params for series lookup: {u'tvdb_id': None, u'tvmaze_id': None, u'name': u'The Daily Show', u'tvrage_id': None}
2015-12-18 23:29 DEBUG    api_tvmaze    Series-Premieres searching db tvmaze_series for the values [(u'tvdb_id', None), (u'tvmaze_id', None), (u'name', u'The Daily Show'), (u'tvrage_id', None)]
2015-12-18 23:29 DEBUG    api_tvmaze    Series-Premieres did not find exact match for series The Daily Show in cache, looking in search table
2015-12-18 23:29 DEBUG    api_tvmaze    Series-Premieres searching lookup table using title The Daily Show
2015-12-18 23:29 DEBUG    api_tvmaze    Series-Premieres found series The Daily Show with Trevor Noah from search table
2015-12-18 23:29 DEBUG    api_tvmaze    Series-Premieres series The Daily Show with Trevor Noah is expired: True
2015-12-18 23:29 DEBUG    api_tvmaze    Series-Premieres trying to fetch series The Daily Show from pytvmaze
2015-12-18 23:29 DEBUG    api_tvmaze    Series-Premieres series The Daily Show with Trevor Noah is already in cache, checking for expiration
2015-12-18 23:29 DEBUG    api_tvmaze    Series-Premieres series The Daily Show with Trevor Noah is expired: True
2015-12-18 23:29 DEBUG    api_tvmaze    Series-Premieres mismatch between series title The Daily Show and search title The Daily Show with Trevor Noah. saving in lookup table
2015-12-18 23:29 ERROR    lazy_lookup   Series-Premieres Unhandled error in lazy lookup plugin
2015-12-18 23:29 CRITICAL manager       Series-Premieres An unexpected crash has occurred. Writing crash report to /home/wolfgang/.download/flexget/crash_report.2015.12.18.232944489526.log
2015-12-18 23:29 DEBUG    manager       Series-Premieres Traceback:
Traceback (most recent call last):
  File "/home/wolfgang/.download/flexget/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/home/wolfgang/.download/flexget/flexget/plugins/metainfo/tvmaze_lookup.py", line 134, in lazy_series_lookup
    entry.update_using_map(self.series_map, series)
  File "/home/wolfgang/.download/flexget/flexget/entry.py", line 266, in update_using_map
    v = value(source_item)
  File "/home/wolfgang/.download/flexget/flexget/plugins/metainfo/tvmaze_lookup.py", line 99, in <lambda>
    'tvmaze_series_episodes': lambda show: [episodes.title for episodes in show.episodes]
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 583, in get
    value = self.callable_(state, passive)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 532, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 602, in _emit_lazyload
    result = q.all()
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2584, in all
    return list(self)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2731, in __iter__
    self.session._autoflush()
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1315, in _autoflush
    util.raise_from_cause(e)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1305, in _autoflush
    self.flush()
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2027, in flush
    self._flush(objects)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2145, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2109, in _flush
    flush_context.execute()
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 785, in _emit_insert_statements
    execute(statement, params)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) UNIQUE constraint failed: tvmaze_lookup.search_name [SQL: u'INSERT INTO tvmaze_lookup (search_name, series_id) VALUES (?, ?)'] [parameters: (u'The Daily Show', 3928)]
```

```
2015-12-18 23:30 DEBUG    if            Series-Premieres NHL - 2015.12.17 - Rangers vs. Wild [ 2015 ] [ MKV | h.264 | WEBRip | 720p | FastTorrent | Internal ] [ Uploader: Anonymous ]  [ NHL.2015.12.17.Rangers.vs.Wild.720p.Away.Feed.GC.WEBRip.AAC2.0.H.264-BTW ] matched requirement tvmaze_series_premiered != None and tvmaze_series_premiered < now - timedelta(days=60)
2015-12-18 23:30 DEBUG    api_tvmaze    Series-Premieres returning search params for series lookup: {u'tvdb_id': None, u'tvmaze_id': None, u'name': u'Nhl', u'tvrage_id': None}
2015-12-18 23:30 DEBUG    api_tvmaze    Series-Premieres searching db tvmaze_series for the values [(u'tvdb_id', None), (u'tvmaze_id', None), (u'name', u'Nhl'), (u'tvrage_id', None)]
2015-12-18 23:30 DEBUG    api_tvmaze    Series-Premieres did not find exact match for series Nhl in cache, looking in search table
2015-12-18 23:30 DEBUG    api_tvmaze    Series-Premieres searching lookup table using title Nhl
2015-12-18 23:30 DEBUG    api_tvmaze    Series-Premieres found series NHL Rivals from search table
2015-12-18 23:30 DEBUG    api_tvmaze    Series-Premieres series NHL Rivals is expired: True
2015-12-18 23:30 DEBUG    api_tvmaze    Series-Premieres trying to fetch series Nhl from pytvmaze
2015-12-18 23:30 DEBUG    api_tvmaze    Series-Premieres creating new series NHL Live in tvmaze_series db
2015-12-18 23:30 DEBUG    api_tvmaze    Series-Premieres mismatch between series title Nhl and search title NHL Live. saving in lookup table
2015-12-18 23:30 ERROR    lazy_lookup   Series-Premieres Unhandled error in lazy lookup plugin
2015-12-18 23:30 CRITICAL manager       Series-Premieres An unexpected crash has occurred. Writing crash report to /home/wolfgang/.download/flexget/crash_report.2015.12.18.233002376671.log
2015-12-18 23:30 DEBUG    manager       Series-Premieres Traceback:
Traceback (most recent call last):
  File "/home/wolfgang/.download/flexget/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/home/wolfgang/.download/flexget/flexget/plugins/metainfo/tvmaze_lookup.py", line 134, in lazy_series_lookup
    entry.update_using_map(self.series_map, series)
  File "/home/wolfgang/.download/flexget/flexget/utils/sqlalchemy_utils.py", line 137, in __exit__
    self.commit()
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 813, in commit
    self.transaction.commit()
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2027, in flush
    self._flush(objects)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2145, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2109, in _flush
    flush_context.execute()
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 785, in _emit_insert_statements
    execute(statement, params)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/wolfgang/.download/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: tvmaze_lookup.search_name [SQL: u'INSERT INTO tvmaze_lookup (search_name, series_id) VALUES (?, ?)'] [parameters: (u'Nhl', 7540)]
```

**Comment by liiight** [comment] 2015-12-19 05:37
This is actually a duplicate of #716 which should be patched very soon, but thanks for the very informative report!

**Closed by liiight** 2015-12-19 05:37 UTC
