### ISSUE TITLE
Unhandled error in plugin metainfo_series: Series flagged invalid

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#1159] opened 2016-05-10 08:02 UTC
```
2016-05-10 09:06 CRITICAL task          download-series-manual-task BUG: Unhandled error in plugin metainfo_series: Series flagged invalid
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 442, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/series.py", line 33, in on_task_metainfo
    self.guess_entry(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/series.py", line 48, in guess_entry
    populate_entry_fields(entry, parsed, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 875, in populate_entry_fields
    entry['series_id'] = parser.pack_identifier
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_common.py", line 551, in pack_identifier
    return self.identifier
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_common.py", line 542, in identifier
    return self.identifiers[0]
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_common.py", line 527, in identifiers
    raise Exception('Series flagged invalid')
Exception: Series flagged invalid
```

**Comment by crawln45** [comment] 2016-05-10 08:04
Without context of the error. That tells us nothing. Please include log file with --loglevel debug and --dump

**Comment by effemmeffe** [comment] 2016-05-10 08:30
Log: http://pastebin.com/5LfNrDCi

**Comment by crawln45** [comment] 2016-05-10 08:34
Guessit flagged it invalid. It's been doing that a lot lately. Not our plugin. nothing we can really do about it. Ask in the guessit github.

**Comment by cvium** [comment] 2016-08-08 12:59
Duplicate of #1098

**Closed by cvium** 2016-08-08 12:59 UTC
