### ISSUE TITLE
The Transmission plugin fails on certain characters in the tvdb_series_name variable

### ISSUE THREAD

**Issue by nohatssir** [Flexget/Flexget#1167] opened 2016-05-12 22:48 UTC
Hey!

When I use the provided configuration and execute the task I get the following error `BUG: Unhandled error in plugin transmission: Can't mix strings and bytes in path components`. The name of the show according to TheTVDB is 'KonoSuba - God’s Blessing on This Wonderful World!!' and I've tracked down the character that causes the error to be the `’` character since it works if I replace that character in `tvdb_series_name` (however, replacing it with for example an `'` or an `´` still fails).

I've also found that if I just change `tvdb_series_name`  to `series_name` or remove it from the `series_path_format` variable It will not cause an error. So `tvdb_series_name` doesn't seem to cause any issues in the `content_filename` directive but only when used in the `path` directive.

Testing configuration (should hopefully be copy pastable except for the transmission details and download directory):

```
templates:

  global:
    pathscrub: windows
    set:
      download_dir: '/mnt/Storage/Downloads'
    transmission:
      host: localhost
      port: 9091
      username: ***
      password: ***
      include_subs: yes
      magnetization_timeout: 120
      main_file_only: yes
      skip_files:
        - '*.nfo'
        - '*.sfv'
        - '*[sS]ample*'
        - '*.txt'

  base_series:
    set:
      series_path: '{{ download_dir }}/Videos/Series'
      series_path_format: '{{ tvdb_series_name }}/{{ tvdb_series_name }} - Season {{ tvdb_season|pad(2) }}'
    thetvdb_lookup: yes
    transmission:
      content_filename: '{{ tvdb_series_name }} [S{{ tvdb_season|pad(2) }}E{{ tvdb_episode|pad(2) }}] {{ tvdb_ep_name|default("Unknown")|replace("/","-") }}'

  anime-series:
    template: base_series
    series:
      settings:
        HorribleSubs:
          from_group: HorribleSubs
          quality: 720p
          path: '{{ series_path }}/{{ series_path_format }}'
      HorribleSubs:
        - Kono Subarashii Sekai ni Shukufuku wo!:
            set:
              tvdb_id: 303867

tasks:
  series-horriblesubs:
    rss: https://feed
    template: anime-series
```

Error log from Arch Linux:

```
2016-05-12 23:34 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 04 [1080p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:34 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 04 [480p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:34 VERBOSE  task          series-horriblesubs ACCEPTED: `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 04 [720p].mkv` by series plugin because matches quality
2016-05-12 23:34 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 03 [1080p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:34 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 03 [480p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:34 VERBOSE  task          series-horriblesubs ACCEPTED: `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 03 [720p].mkv` by series plugin because matches quality
2016-05-12 23:34 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 02 [1080p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:34 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 02 [480p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:34 VERBOSE  task          series-horriblesubs ACCEPTED: `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 02 [720p].mkv` by series plugin because matches quality
2016-05-12 23:34 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 01 [1080p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:34 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 01 [480p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:34 VERBOSE  task          series-horriblesubs ACCEPTED: `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 01 [720p].mkv` by series plugin because matches quality
2016-05-12 23:34 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 10 [720p].mkv
2016-05-12 23:34 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 09 [720p].mkv
2016-05-12 23:34 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 08 [720p].mkv
2016-05-12 23:34 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 07 [720p].mkv
2016-05-12 23:34 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 06 [720p].mkv
2016-05-12 23:34 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 05 [720p].mkv
2016-05-12 23:34 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 04 [720p].mkv
2016-05-12 23:34 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 03 [720p].mkv
2016-05-12 23:34 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 02 [720p].mkv
2016-05-12 23:34 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 01 [720p].mkv
2016-05-12 23:34 VERBOSE  details       series-horriblesubs Summary - Accepted: 10 (Rejected: 0 Undecided: 20 Failed: 0)
2016-05-12 23:34 INFO     transmission  series-horriblesubs "[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 10 [720p].mkv" torrent added to transmission
2016-05-12 23:34 CRITICAL task          series-horriblesubs BUG: Unhandled error in plugin transmission: Can't mix strings and bytes in path components
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/flexget/task.py", line 442, in __run_plugin
    return method(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/flexget/plugins/plugin_transmission.py", line 298, in on_task_output
    self.add_to_transmission(self.client, task, config)
  File "/home/user/.local/lib/python3.5/site-packages/flexget/plugins/plugin_transmission.py", line 523, in add_to_transmission
    file_path = os.path.dirname(os.path.join(download_dir, fl[r.id][main_id]['name']))
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 145, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

Error log from Debian Jessie (differing a little, I'm guessing that's because of the Python version?):

```
2016-05-12 23:52 VERBOSE  details       series-horriblesubs Produced 30 entries.
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 10 [1080p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 10 [480p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  task          series-horriblesubs ACCEPTED: `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 10 [720p].mkv` by series plugin because matches quality
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 09 [1080p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 09 [480p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  task          series-horriblesubs ACCEPTED: `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 09 [720p].mkv` by series plugin because matches quality
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 08 [1080p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 08 [480p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  task          series-horriblesubs ACCEPTED: `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 08 [720p].mkv` by series plugin because matches quality
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 07 [1080p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 07 [480p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  task          series-horriblesubs ACCEPTED: `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 07 [720p].mkv` by series plugin because matches quality
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 06 [1080p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 06 [480p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  task          series-horriblesubs ACCEPTED: `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 06 [720p].mkv` by series plugin because matches quality
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 05 [1080p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 05 [480p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  task          series-horriblesubs ACCEPTED: `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 05 [720p].mkv` by series plugin because matches quality
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 04 [1080p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 04 [480p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  task          series-horriblesubs ACCEPTED: `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 04 [720p].mkv` by series plugin because matches quality
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 03 [1080p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 03 [480p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  task          series-horriblesubs ACCEPTED: `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 03 [720p].mkv` by series plugin because matches quality
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 02 [1080p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 02 [480p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  task          series-horriblesubs ACCEPTED: `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 02 [720p].mkv` by series plugin because matches quality
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 01 [1080p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  series        series-horriblesubs Ignored `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 01 [480p].mkv`. Does not meet quality requirement `720p`.
2016-05-12 23:52 VERBOSE  task          series-horriblesubs ACCEPTED: `[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 01 [720p].mkv` by series plugin because matches quality
2016-05-12 23:52 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 10 [720p].mkv
2016-05-12 23:52 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 09 [720p].mkv
2016-05-12 23:52 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 08 [720p].mkv
2016-05-12 23:52 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 07 [720p].mkv
2016-05-12 23:52 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 06 [720p].mkv
2016-05-12 23:52 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 05 [720p].mkv
2016-05-12 23:52 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 04 [720p].mkv
2016-05-12 23:52 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 03 [720p].mkv
2016-05-12 23:52 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 02 [720p].mkv
2016-05-12 23:52 INFO     download      series-horriblesubs Downloading: [HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 01 [720p].mkv
2016-05-12 23:52 VERBOSE  details       series-horriblesubs Summary - Accepted: 10 (Rejected: 0 Undecided: 20 Failed: 0)
2016-05-12 23:52 INFO     transmission  series-horriblesubs "[HorribleSubs] Kono Subarashii Sekai ni Shukufuku wo! - 10 [720p].mkv" torrent added to transmission
2016-05-12 23:52 CRITICAL task          series-horriblesubs BUG: Unhandled error in plugin transmission: 'ascii' codec can't decode byte 0xe2 in position 82: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/flexget/task.py", line 442, in __run_plugin
    return method(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/flexget/plugins/plugin_transmission.py", line 298, in on_task_output
    self.add_to_transmission(self.client, task, config)
  File "/home/user/.local/lib/python2.7/site-packages/flexget/plugins/plugin_transmission.py", line 523, in add_to_transmission
    file_path = os.path.dirname(os.path.join(download_dir, fl[r.id][main_id]['name']))
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 82: ordinal not in range(128)
```

Thanks!

**Comment by nohatssir** [comment] 2016-09-20 00:28
I'm by no means any Python expert or familiar with your codebase, so this is probably not the right way to solve it. But I can make it work as expected by changing this [line](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/clients/transmission.py#L546) from `pathscrub(filename + file_ext)).encode('utf-8')` to `pathscrub(filename + file_ext))`. It doesn't seem like the rename_torrent_path function likes getting called with a byte string.

**Comment by cvium** [comment] 2016-11-12 13:54
Can't reproduce the first issue with path joins, so I'm closing this as the second issue is a duplicate of #1264

**Closed by cvium** 2016-11-12 13:54 UTC
