### ISSUE TITLE
descargas2020 plugin broken (again)

### ISSUE THREAD

**Issue by Aokromes** [Flexget/Flexget#2335] opened 2019-02-09 15:06 UTC
### Expected behaviour:
it downloads torrent properly.

### Steps to reproduce:
add this rss http://feeds.feedburner.com/descargas2020new
flexget execute
you will get:
2019-02-09 16:00 INFO     download      series_sigo     Downloading: Single Parents (Proper) - Temporada 1  [HDTV 720p][Cap.109][AC3 5.1 Castellano][]
2019-02-09 16:00 ERROR    entry         series_sigo     Failed Single Parents (Proper) - Temporada 1  [HDTV 720p][Cap.109][AC3 5.1 Castellano][] (Unexpected html content received from https://descargas2020.com/descargar/serie-en-hd/single-parents/temporada-1/capitulo-09/ - maybe a login page?)
2019-02-09 16:00 INFO     task          series_sigo     Rerunning the task in case better resolution can be achieved.

#### Config:

```
tasks:
  series_sigo:
    rss:
      url: http://feeds.feedburner.com/descargas2020new
      link: link
    all_series: yes
    seen: local
    regexp:
      reject:
        - PCDVD
    accept_all: yes
    thetvdb_lookup: yes
    no_entries_ok: yes
    set:
      filename: "{{title|pathscrub}}.torrent"
    download: /home/flexget/torrent/
```
  
#### Log:

2019-02-09 16:00 INFO     download      series_sigo     Downloading: Single Parents (Proper) - Temporada 1  [HDTV 720p][Cap.109][AC3 5.1 Castellano][]
2019-02-09 16:00 ERROR    entry         series_sigo     Failed Single Parents (Proper) - Temporada 1  [HDTV 720p][Cap.109][AC3 5.1 Castellano][] (Unexpected html content received from https://descargas2020.com/descargar/serie-en-hd/single-parents/temporada-1/capitulo-09/ - maybe a login page?)
2019-02-09 16:00 INFO     task          series_sigo     Rerunning the task in case better resolution can be achieved.

```
paste log output here
```
</details>

### Additional information:

- FlexGet version: 2.19.5
- Python version: 2.7.13
- Installation method: i don't remember
- Using daemon (yes/no): no
- OS and version: debian 9 x64
- Link to crash log:

**Comment by daveraver** [comment] 2019-02-10 18:57
Hi to all, same here, with flexget 2.19.6 and instalation made with pip3. I read that it may be solved with some web content plugin of flexget??? cookies/header/authentication plugin?? No idea of this... I am using ubuntu bionic armhf. 

Greetings,
David

**Comment by daveraver** [comment] 2019-02-10 19:00
``The Good Doctor - Temporada 2  [HDTV 720p][Cap.213][V.O. Subt. Castellano][www.pctnew.com]` by retry_failed plugin because waiting before retrying entry which has failed in the past. (failure reason: Unexpected html content received from `https://descargas2020.com/descargar/serie-vo/the-good-doctor/temporada-2/capitulo-13/` - maybe a login page?)
`

**Comment by davidcsgf** [comment] 2019-02-10 19:01
More information about the error

> 2019-02-10 19:41 DEBUG    urlrewriter   tv-spanish      Url rewriting http://descargas2020.com/descargar/serie/the-expanse/temporada-3/capitulo-01-al-06/
2019-02-10 19:41 VERBOSE  descargas2020 tv-spanish      Descargas2020 URL: http://descargas2020.com/descargar/serie/the-expanse/temporada-3/capitulo-01-al-06/
2019-02-10 19:41 ERROR    urlrewriter   tv-spanish      'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/components/sites/urlrewriting.py", line 71, in url_rewrite
    urlrewriter.instance.url_rewrite(task, entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/components/sites/sites/descargas2020.py", line 50, in url_rewrite
    entry['url'] = self.parse_download_page(entry['url'], task)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 119, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/components/sites/sites/descargas2020.py", line 57, in parse_download_page
    page = self.requests.get(url)
AttributeError: 'NoneType' object has no attribute 'get'
2019-02-10 19:41 WARNING  urlrewriter   tv-spanish      descargas2020: Internal error with url http://descargas2020.com/descargar/serie/the-expanse/temporada-3/capitulo-01-al-06/
2019-02-10 19:41 DEBUG    entry         tv-spanish      Marking entry 'The Expanse -  [HDTV][3x01_306][Castellano][www.pctnew.com]' as failed
2019-02-10 19:41 ERROR    entry         tv-spanish      Failed The Expanse -  [HDTV][3x01_306][Castellano][www.pctnew.com] (None)
2019-02-10 19:41 VERBOSE  task          tv-spanish      FAILED: `The Expanse -  [HDTV][3x01_306][Castellano][www.pctnew.com]` by urlrewriting plugin

**Comment by daveraver** [comment] 2019-02-10 19:03
> 

> More information about the error
> 
> > 2019-02-10 19:41 DEBUG    urlrewriter   tv-spanish      Url rewriting http://descargas2020.com/descargar/serie/the-expanse/temporada-3/capitulo-01-al-06/
> > 2019-02-10 19:41 VERBOSE  descargas2020 tv-spanish      Descargas2020 URL: http://descargas2020.com/descargar/serie/the-expanse/temporada-3/capitulo-01-al-06/
> > 2019-02-10 19:41 ERROR    urlrewriter   tv-spanish      'NoneType' object has no attribute 'get'
> > Traceback (most recent call last):
> > File "/usr/local/lib/python2.7/dist-packages/flexget/components/sites/urlrewriting.py", line 71, in url_rewrite
> > urlrewriter.instance.url_rewrite(task, entry)
> > File "/usr/local/lib/python2.7/dist-packages/flexget/components/sites/sites/descargas2020.py", line 50, in url_rewrite
> > entry['url'] = self.parse_download_page(entry['url'], task)
> > File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 119, in wrapped_func
> > return func(*args, **kwargs)
> > File "/usr/local/lib/python2.7/dist-packages/flexget/components/sites/sites/descargas2020.py", line 57, in parse_download_page
> > page = self.requests.get(url)
> > AttributeError: 'NoneType' object has no attribute 'get'
> > 2019-02-10 19:41 WARNING  urlrewriter   tv-spanish      descargas2020: Internal error with url http://descargas2020.com/descargar/serie/the-expanse/temporada-3/capitulo-01-al-06/
> > 2019-02-10 19:41 DEBUG    entry         tv-spanish      Marking entry 'The Expanse -  [HDTV][3x01_306][Castellano][www.pctnew.com]' as failed
> > 2019-02-10 19:41 ERROR    entry         tv-spanish      Failed The Expanse -  [HDTV][3x01_306][Castellano][www.pctnew.com] (None)
> > 2019-02-10 19:41 VERBOSE  task          tv-spanish      FAILED: `The Expanse -  [HDTV][3x01_306][Castellano][www.pctnew.com]` by urlrewriting plugin

this url rewriter is an error of 2018 december, I think, And it was solved in a few days. Now the problem is that rss ask for login data... and it dont let to donwload the torrent

**Comment by davidcsgf** [comment] 2019-02-10 19:18
this happens with the rss's:
-http://feeds.feedburner.com/descargas2020
-http://feeds.feedburner.com/descargas2020new

**Comment by daveraver** [comment] 2019-02-10 19:20
this one 

-http://feeds.feedburner.com/descargas2020new

thanks

**Comment by Aokromes** [comment] 2019-02-10 20:57
maybe https://github.com/Jackett/Jackett/pull/4630/files can help fixing this time.

**Comment by daveraver** [comment] 2019-02-12 17:02
maybe we must reinstall flexget, some people is working with this rss as usual, no problem, they say

**Comment by malomehi** [comment] 2019-02-12 19:00
One issue is that the plugin does not accept https urls, only http.
The other issue is that `self.requests` value is found as `None` when used in parsing fucntion.
I made a fix and works for me. See changes here:
https://github.com/Flexget/Flexget/pull/2337/files

**Comment by Rafa-and** [comment] 2019-02-12 20:19
> One issue is that the plugin does not accept https urls, only http.
> The other issue is that `self.requests` value is found as `None` when used in parsing fucntion.
> I made a fix and works for me. See changes here:
> https://github.com/Flexget/Flexget/pull/2337/files

In my case, it works fine again applying the http|https solution.
If I also apply the self.requests condition, then it abends.

**Comment by malomehi** [comment] 2019-02-12 20:27
> > One issue is that the plugin does not accept https urls, only http.
> > The other issue is that `self.requests` value is found as `None` when used in parsing fucntion.
> > I made a fix and works for me. See changes here:
> > https://github.com/Flexget/Flexget/pull/2337/files
> 
> In my case, it works fine again applying the http|https solution.
> If I also apply the self.requests condition, then it abends.

Weird, in my case I need both fixes. Anyway, happy that the https addition is useful for you.

**Comment by gazpachoking** [comment] 2019-02-12 22:52
Closing this as it's reported #2337 fixes. Let's open another ticket and try again if not.

**Closed by gazpachoking** 2019-02-12 22:52 UTC
