### ISSUE TITLE
Error downloading from newpct

### ISSUE THREAD

**Issue by javifm86** [Flexget/Flexget#1997] opened 2017-11-02 08:25 UTC
### Expected behaviour:
Download last episodes from my series from newpct feed.

### Actual behaviour:
Download from newpct is not working. I get this message:
 URL rewriting newpct failed: Unable to locate torrent ID from url http://www.newpct.com/descargar-seriehd/the-good-doctor/capitulo-13/hdtv-720p-ac3-5-1/

### Steps to reproduce:
- Step 1: flexget execute

#### Config:
```
tasks:
  series_sigo:
    rss: http://feeds2.feedburner.com/newpctorrent
    regexp:
      reject:
        - V.O. Subt. Castellano
    series:
      settings:
        calidadnormal:
          sequence_regexp: Cap.(\d+)
          quality: <720p
        calidadhd:
          sequence_regexp: Cap.(\d+)
          quality: 720p+
      calidadhd:
        - The Walking Dead
        - The Good Doctor
        - Absentia
    transmission:
      host: 192.168.1.60
      port: 9091
      ratio: 50
      path: /media/TOSHIBA/Series/{{series_name}}
      username: myUserName
      password: myPassword
      skip_files:
        - '*.nfo'
        - '*.sfv'
        - '[sS]ample*'
        - '*.txt'
        - '*.url'
        - '*.html'
        - '*.htm'
```
  
#### Log:
```
2017-11-02 09:14 VERBOSE  task          series_sigo     ACCEPTED: `The Good Doctor - Temporada 1 [HDTV 720p][Cap.103][AC3 5.1 Español Castellano]` by series plugin because matches quality
2017-11-02 09:14 VERBOSE  newpct        series_sigo     Newpct URL: http://www.newpct.com/descargar-seriehd/the-good-doctor/capitulo-13/hdtv-720p-ac3-5-1/
2017-11-02 09:14 WARNING  urlrewriter   series_sigo     URL rewriting newpct failed: Unable to locate torrent ID from url http://www.newpct.com/descargar-seriehd/the-good-doctor/capitulo-13/hdtv-720p-ac3-5-1/
```

### Additional information:

- FlexGet version: 2.10.104
- Python version: 2.7.9
- Installation method: pip repository (also tried github install with virtualenv, from develop and same result)
- Using daemon (yes/no): no
- OS and version: Raspbian on raspberry pi 3

**Comment by Aokromes** [comment] 2017-11-02 08:35
Confirmed.

**Comment by cvium** [comment] 2017-11-10 18:37
Fixed in 7c2e018b03dd0d4133e32910224744f69ab196d8

**Closed by cvium** 2017-11-10 18:37 UTC

**Comment by ciltocruz** [comment] 2018-01-04 12:58
Can you open this topic? Newpct fails again because Newpct has changed its html code.

**Comment by liiight** [comment] 2018-01-04 13:00
https://github.com/Flexget/Flexget/pull/2054 was just merged

**Comment by cvium** [comment] 2018-01-04 13:22
New bug, new issue. Please don't "necro" old issues. It only makes it harder to track.
