### ISSUE TITLE
Plugin `flexget.plugins.operate.verify_ssl_certificates` failed to import dependencies

### ISSUE THREAD

**Issue by Vallle** [Flexget/Flexget#1846] opened 2017-05-27 08:47 UTC
### Expected behaviour:

Running 'flexget execute' every hour to check for new items and successfully add them to Deluge.

### Actual behaviour:

'flexget execute' fails to complete due to critical error.

### Steps to reproduce:
- Step 1: Run command 'flexget execute' or 'flexget check' and see an immediate error.

#### Config:
```
templates:
  tv:
    series:
      - "Marvel's Agents of S.H.I.E.L.D.":
          upgrade: yes
          quality: 720p+ hdtv+
          name_regexp: ^marvel(')?s.agents.of.(s.h.i.e.l.d.?|shield)
      - Brooklyn Nine-Nine:
          upgrade: yes
          quality: 720p+ hdtv+
      - It's Always Sunny in Philadelphia:
          alternate_name: Its Always Sunny in Philadelphia
          upgrade: yes
          quality: 720p+ hdtv+
      - Vice Principals:
          upgrade: yes
          quality: 720p+ hdtv+
      - The Night Of:
          upgrade: yes
          quality: 720p+ hdtv+
      - Westworld:
          upgrade: yes
          quality: 720p+ hdtv+
      - The Grand Tour:
          upgrade: yes
          quality: 1080p
      - Taboo:
          upgrade: yes
          quality: 720p+ hdtv+
      - Legion:
          upgrade: yes
          quality: 720p+ hdtv+
      - American Gods:
          upgrade: yes
          quality: 720p+ webrip+
      - The Handmaid's Tale:
          upgrade: yes
          quality: 720p+ webrip+


tasks:      
  mTv task:
    rss: https://www.morethan.tv/feeds.php?feed=authkeysthatactuallywork
    template: tv
    download: E:\Storage\
    deluge:
      main_file_only: yes
      queuetotop: yes
      label: mtv
```
  
#### Log:
```
C:\WINDOWS\system32>flexget execute
2017-05-27 10:42 CRITICAL plugin                        Plugin `flexget.plugins.operate.verify_ssl_certificates` failed to import dependencies
Traceback (most recent call last):
  File "d:\programs\python27\lib\site-packages\flexget\plugin.py", line 396, in _load_plugins_from_dirs
    __import__(module_name)
  File "d:\programs\python27\lib\site-packages\flexget\plugins\operate\verify_ssl_certificates.py", line 5, in <module>
    from requests.packages import urllib3
ImportError: No module named packages
2017-05-27 10:42 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2017-05-27 10:42 CRITICAL task          mTv task        Plugin `deluge` cannot be used because dependency `deluge` is missing.
2017-05-27 10:42 WARNING  task          mTv task        Aborting task (plugin: deluge)

C:\WINDOWS\system32>flexget check
2017-05-27 10:42 CRITICAL plugin                        Plugin `flexget.plugins.operate.verify_ssl_certificates` failed to import dependencies
Traceback (most recent call last):
  File "d:\programs\python27\lib\site-packages\flexget\plugin.py", line 396, in _load_plugins_from_dirs
    __import__(module_name)
  File "d:\programs\python27\lib\site-packages\flexget\plugins\operate\verify_ssl_certificates.py", line 5, in <module>
    from requests.packages import urllib3
ImportError: No module named packages
2017-05-27 10:42 VERBOSE  check                         Pre-checked 113 configuration lines
2017-05-27 10:42 VERBOSE  check                         Checking config file `C:\Users\BJ\flexget\config.yml`
2017-05-27 10:42 VERBOSE  check                         Config passed check.
```

### Additional information:

- FlexGet version: 2.10.54
- Python version: 2.7.13
- Installation method: pip (as instructed at https://flexget.com/InstallWizard/Windows)
- Using daemon (yes/no): No. Using task scheduler.
- OS and version: Microsoft Windows [Version 10.0.15063]

**Comment by SmartFinn** [comment] 2017-05-27 08:54
Requests 2.16.0 has been released with breaking changes https://github.com/kennethreitz/requests/issues/4069

#### Workaround:

```
pip install requests==2.15.1
```

**Comment by kennethreitz** [comment] 2017-05-27 13:47
2.16.1 released, which fixes this.

**Closed** 2017-05-27 14:16 UTC

**Comment by kennethreitz** [comment] 2017-05-27 15:09
Requests v2.16.2 is now out, which should be completely backwards compatible. Sorry for the hiccups!
✨🍰✨

**Comment by cvium** [comment] 2017-05-27 19:02
@kennethreitz looks like v2.16.2+ broke some stuff for us that worked in 2.16.1

**Comment by kennethreitz** [comment] 2017-05-27 19:03
@cvium can you be specific?

**Comment by cvium** [comment] 2017-05-27 19:04
@kennethreitz I'm not sure what makes it break, but our tests fail with 2.16.2+. See here https://travis-ci.org/Flexget/Flexget/jobs/236710884 (dunno if this is public).

**Comment by kennethreitz** [comment] 2017-05-27 19:07
@cvium hmm, i'm seeing lots of failures, but nothing that should be caused by this — you should be seeing import errors if anything was caused by this.

**Comment by cvium** [comment] 2017-05-27 19:08
@kennethreitz All I can say is that 2.15.1 and 2.16.1 work. v2.16.2 and onward causes all those errors :/

**Comment by kennethreitz** [comment] 2017-05-27 19:09
@cvium if you want to help, try to get me a small chunk of code that works for you on 2.16.1 and fails on 2.16.2.

**Comment by kennethreitz** [comment] 2017-05-27 19:15
@cvium running your test suite locally... will let you know if i come up with anything.

**Comment by cvium** [comment] 2017-05-27 19:18
@kennethreitz This fails for me on the newest version.

```
import requests
requests.get('http://labs.silverorange.com/local/solabs/rsstest/httpauth/rss_with_auth.xml', timeout=60, headers={}, auth=('testuser', 'testpass'))
```

**Comment by kennethreitz** [comment] 2017-05-27 19:21
@cvium that's failing for me for any version of Requests.

**Comment by cvium** [comment] 2017-05-27 19:23
Oh. Hmm, maybe the newest version of requests doesn't work with vcrpy? All of our online tests are really just played back by VCR cassettes and the tests that are now failing in our suite properly don't work anymore.

**Comment by kennethreitz** [comment] 2017-05-27 19:24
@cvium ah, interesting. I'll check it out!

**Comment by kennethreitz** [comment] 2017-05-27 19:25
i'd open an issue with [vcrpy](https://github.com/kevin1024/vcrpy/issues) if that's the case

**Comment by kennethreitz** [comment] 2017-05-27 19:36
I opened an issue for you. Hope I'm being helpful!

**Comment by cvium** [comment] 2017-05-27 19:54
Thanks. Hopefully they can provide an answer.

**Comment by kevin1024** [comment] 2017-05-28 03:02
Please give it a try with the newest release of vcrpy, 1.11.1 :)

**Comment by cvium** [comment] 2017-05-28 06:13
Seems to be working now. Cheers.

**Comment by kennethreitz** [comment] 2017-05-28 06:14
\o/

**Comment by kennethreitz** [comment] 2017-05-28 06:14
Sorry for the headdache. Tis the cost of progress!
