### ISSUE TITLE
BUG: Discover / api_bluray: "'NoneType' object has no attribute 'lower'"

### ISSUE THREAD

**Issue by wtluke** [Flexget/Flexget#1354] opened 2016-08-18 13:47 UTC
This just cropped up in 2.3.0:

```
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 472, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 289, in on_task_input
    entries = self.estimated(entries, estimation_mode)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 201, in estimated
    est_date = estimator.estimate(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_released.py", line 28, in estimate
    estimate = estimator(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_released_movies_bluray.py", line 31, in estimate
    movie = lookup(title=movie_name, year=movie_year, session=session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_bluray.py", line 212, in lookup
    if title.lower() != movie.name.lower():
AttributeError: 'NoneType' object has no attribute 'lower'
```

```
  moviesPBHQ:
    verify_ssl_certificates: no
    discover:
      what:
        - movie_list:
            list_name: allmyfilms
            strip_year: yes
      from:
        - piratebay:
            category: movies
    template: movietemplate
    priority: 80
    seen: local
    quality:
      - 720p+
      - webrip+
```

Let me know if you need more details

**Comment by Tommatheussen** [comment] 2016-08-18 13:50
Duplicate of #1352 
Fix is in develop, release in few hours will have it fixed.

**Closed by Tommatheussen** 2016-08-18 13:50 UTC
