### ISSUE TITLE
kodi_library plugin does not allow localhost, only full address http://1.2.3.4

### ISSUE THREAD

**Issue by zilexa** [Flexget/Flexget#2285] opened 2018-12-27 20:17 UTC
This is just a minor one, when flexget and kodi are installed on the same device.
works (only with http://):
```
    kodi_library:
      action: clean
      category: video
      url: http://192.168.1.10
      port: 8080    
```
does not work:
```
    kodi_library:
      action: clean
      category: video
      url: localhost
      port: 8080
```
other plugins like transmission allow `localhost` instead of full address.

**Comment by paranoidi** [comment] 2019-01-04 01:11
@cvium  what's with "Not A Bug" label? :)

Let's just close the issues.

**Closed by paranoidi** 2019-01-04 01:11 UTC
Labels: Not A Bug

**Comment by gazpachoking** [comment] 2019-01-06 01:38
@zilexa You can use http://localhost
