### ISSUE TITLE
Missing notifications - g-io-error-quark: Cannot autolanch dbus

### ISSUE THREAD

**Issue by hhiru** [Flexget/Flexget#1830] opened 2017-05-19 19:45 UTC
### Expected behaviour:
Receiving notifications when new entries are accepted

### Actual behaviour:
No notification sent

#### Config:
```
templates:
  global:
    notify:
      entries:
        title: New episode downloading!
        what: accepted
        via:
          - toast: yes
```
  
### Additional information:

- FlexGet version: 2.10.47
- Python version: 2.7.13
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Solus
- Link to crash log:

**Comment by crawln45** [comment] 2017-05-19 22:36
well the problem is you can't use a notification system on a headless linux box. Meaning you have no x11 display activated while trying to use the notification system.

**Comment by hhiru** [comment] 2017-05-20 11:16
So how can I solve this problem?

**Comment by crawln45** [comment] 2017-05-20 18:24
Means you have no desktop to send the notifications to.

**Comment by cvium** [comment] 2017-11-10 18:48
Since no one else seems to have this problem I'm closing the issue.

**Closed by cvium** 2017-11-10 18:48 UTC
Labels: Non-Flexget Resource
