### ISSUE TITLE
`series list` command cuts of series name with --porcelain option

### ISSUE THREAD

**Issue by danielkza** [Flexget/Flexget#1303] opened 2016-07-30 06:08 UTC
### Expected behaviour:

Series names are always printed unabbreviated with the `--porcelain` option.
 
### Actual behaviour:

Series names are still abbreviated.

### Steps to reproduce:
- Step 1: Add a series with a long name.
  `flexget series begin 'Aqua Something You Know Whatever' S01E01`
- Step 2: Check the list of series in porcelain mode.
  `flexget series list all --porcelain`
```
Name                           | Latest     | Age        | Downloaded          
Aqua Something You Know Wha... | N/A        | N/A        | N/A          
```

### Additional information:

- Flexget Version: 2.2.1
- Python Version: 2.7.12
- Installation method: pip
- OS and version: Fedora 24 x86_64

**Comment by liiight** [comment] 2016-07-30 06:54
That's kinda by design. Did you consider using API?

**Comment by danielkza** [comment] 2016-07-30 07:03
> That's kinda by design.

What is the usefulness of shortening with the porcelain mode? It breaks the expectation that I can feed it's output back to other commands. 

>  Did you consider using API?

I just wanted to write a command that looped through all the series and showed them. Seems like the API is overkill for that case.

**Comment by liiight** [comment] 2016-07-30 08:30
I guess you have a point, ill see about expanding it dynamically.

**Comment by cvium** [comment] 2016-08-20 14:12
Since #1311 has been merged, this issue should be fixed. Re-open if not.

**Closed by cvium** 2016-08-20 14:12 UTC
Labels: Bug
