### ISSUE TITLE
Trakt Authentication

### ISSUE THREAD

**Issue by Aidanb79** [Flexget/Flexget#921] opened 2016-03-04 16:56 UTC
Hi,

I am trying to authorise flexget to use Trakt but when i run the command flexget trakt auth <account> <pin> i get this error message.

Warning: PIN authorization has been deprecated. Use Device Authorization instead.
Authorization failed: Token exchange with trakt failed: 403 Client Error: Forbidden for url: https://api-v2launch.trakt.tv/oauth/token

I have added the account which is my username in to the config.yml but still doesn't work.

I am using flexget version 1.2.471 and i have restarted the deamon too if that helps.

Regards

Aidan

**Comment by cvium** [comment] 2016-03-04 17:03
Try `flexget trakt auth <account>` instead.

**Comment by Aidanb79** [comment] 2016-03-04 17:05
Hi,

I get; Authorization failed: Device authorization with Trakt.tv failed: 403 Client Error: Forbidden for url: https://api-v2launch.trakt.tv/oauth/device/code

Regards

Aidan

**Comment by cvium** [comment] 2016-03-04 18:30
It works for me, so I don't think it's a Flexget issue. I can't reproduce it.

Have you tried rebooting?

**Comment by Aidanb79** [comment] 2016-03-04 20:37
Hi, I have rebooted and still I get the same errors, this is the first time I have tried running it. I have run flexget trakt show and get No trakt authorizations stored in database.

**Comment by cvium** [comment] 2016-03-04 20:50
Are you using a VPN or something similar?

**Comment by Aidanb79** [comment] 2016-03-04 20:55
Yes I do use a vpn would this effect it?

**Comment by cvium** [comment] 2016-03-04 20:56
I had the same problem when my VPN wasn't configured properly. Try without VPN.

**Comment by Aidanb79** [comment] 2016-03-04 21:00
Hi, 

I have turned the vpn off and have tried again still the same respond back its like trakt api isn't working?

Regards

Aidan

**Comment by cvium** [comment] 2016-03-04 21:01
Disable the VPN service and reboot. Then try again.

Trakt API is working. I have been able to authorize multiple times in the last 3 hours.

**Comment by Aidanb79** [comment] 2016-03-04 21:26
Hi, I have done that and it worked. 
The problem now is, I have restarted the vpn and ran the test and I get 
 Error during input plugin trakt_list: Device authorization with Trakt.tv failed: 403 Client Error: Forbidden for url: https://api-v2launch.trakt.tv/oauth/device/code
I stopped it and get Error during input plugin trakt_list: Device authorization with Trakt.tv failed: 503 Server Error: Service Unavailable: Back-end server is at capacity for url: https://api-v2launch.trakt.tv/oauth/device/code.

How do I configure my vpn to work with it?

**Comment by cvium** [comment] 2016-03-04 21:33
I am not sure what fixed it for me. I added the following to the OpenVPN config
```
persist-key
persist-tun
tls-client
remote-cert-tls server
auth-nocache
```
and then I set the DNS to Google DNS. Haven't had the problem since, but if this fixed it or it was by chance, I have no idea.

Anyway, closing the issue as it is not a problem with Flexget. You can open a thread on the forum if you wish to get more help (http://discuss.flexget.com)

**Closed by cvium** 2016-03-04 21:33 UTC
