### ISSUE TITLE
piping flexget series list crashes

### ISSUE THREAD

**Issue by mourningsun75** [Flexget/Flexget#1508] opened 2016-11-19 12:08 UTC
### Expected behaviour:
piping the list of series to file not crashing
### Actual behaviour:
Could not start manager: 'ascii' codec can't encode character u'\xe4' in position 3350: ordinal not in range(128)

### Steps to reproduce:
- Step 1: ...
Just call flexget series list | less
#### Config:
nothing relevant
 
#### Log:
```logtalk
========= Remote Traceback (2) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 90, in exposed_handle_cli
    self.manager.handle_cli(options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 353, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/series.py", line 35, in do_cli
    display_summary(options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/series.py", line 107, in display_summary
    console(table.output)
  File "/usr/local/lib/python2.7/dist-packages/flexget/terminal.py", line 270, in console
    print(text, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 51, in write
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 57, in flush
    self.writer(self.buffer, end='')
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 3350: ordinal not in range(128)

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 117, in exposed_console
    console(text, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/terminal.py", line 270, in console
    print(text, *args, **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 3350: ordinal not in range(128)
```
### Additional information:

- Flexget Version: 2.6.1
- Python Version: 2.7
- Installation method: python pip
- OS and version: linux mint 18
- Link to crash log:

**Comment by mourningsun75** [comment] 2016-11-19 12:13
flexget series show also crashes

**Comment by cvium** [comment] 2016-11-19 12:16
And what does it show without piping?

**Comment by mourningsun75** [comment] 2016-11-19 12:57
The expected list of shows

**Comment by mourningsun75** [comment] 2016-12-22 08:45
Will this be fixed?

**Comment by liiight** [comment] 2016-12-22 08:49
yes. there's a whole bunch of unicode and terminal related stuff, we're looking into the proper solution for all.

**Comment by liiight** [comment] 2016-12-22 10:05
Related #1558

**Comment by liiight** [comment] 2017-01-03 11:59
When you run this without the less, does it replace some non ascii characters of your shows with `?`?

**Comment by mourningsun75** [comment] 2017-01-03 13:16
no, without less everything looks ok.
i.e.
Der kleine Eisbär

**Comment by liiight** [comment] 2017-01-03 13:55
Can you run with debug flag? Some new logs were added recently that may be relevant

**Comment by mourningsun75** [comment] 2017-01-03 19:20
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 310, in start
    client.handle_cli(self.args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 2568: ordinal not in range(128)

========= Remote Traceback (2) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 85, in exposed_handle_cli
    self.manager.handle_cli(options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 354, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/series.py", line 35, in do_cli
    display_summary(options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/series.py", line 107, in display_summary
    console(table.output)
  File "/usr/local/lib/python2.7/dist-packages/flexget/terminal.py", line 270, in console
    print(text, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 46, in write
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 52, in flush
    self.writer(self.buffer, end='')
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 2568: ordinal not in range(128)

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 112, in exposed_console
    console(text, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/terminal.py", line 270, in console
    print(text, *args, **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 2568: ordinal not in range(128)

```

**Comment by tobbez** [comment] 2017-01-03 22:33
As a data point, this used to work in 1.x (at least in 1.2.481/Python 2.7 - I tried it before I upgraded).

The below applies to 2.8.17/Python 2.7.

Relevant entries from a debug log (the entries are identical both with and without piping):
```
DEBUG    manager                       sys.defaultencoding: ascii
DEBUG    manager                       sys.getfilesystemencoding: UTF-8
DEBUG    manager                       flexget detected io encoding: utf-8
DEBUG    manager                       os.path.supports_unicode_filenames: False
```

The issue should be trivially reproducible by injecting a series with non-ascii characters, and then piping the output of `flexget series list` into anything (e.g. `flexget series list | cat -`).

This type of issue is usually seen because Python's behaves differently when stdout is a pipe (and not a terminal).

**Comment by grr** [comment] 2017-01-06 05:39
Same related error `failed list` (#1580) and `history` (#1223). These same errors keep regressing- there should be tests to check for this. and why do they only get fixed for a single command at a time instead of fixing this at the root?

**Comment by gazpachoking** [comment] 2017-01-06 17:15
> Same related error failed list (#1580) and history (#1223). These same errors keep regressing- there should be tests to check for this. and why do they only get fixed for a single command at a time instead of fixing this at the root?

I can assure you nobody is breaking things on purpose. Stuff like this is tough, because it depends highly on the user's environment. If you have some good insight on how this can be fixed at the root, or a good way to implement tests, a PR would be much appreciated.

**Comment by tobbez** [comment] 2017-01-26 18:02
## This issue 

The issue here is that the current handling of charset fallback in `console` is incorrect.

The current code ([flexget/terminal.py](https://github.com/Flexget/Flexget/blob/develop/flexget/terminal.py#L256):256):
```python
def console(text, *args, **kwargs):
    """
    Print to console safely. Output is able to be captured by different streams in different contexts.

    Any plugin wishing to output to the user's console should use this function instead of print so that
    output can be redirected when FlexGet is invoked from another process.

    Accepts arguments like the `print` function does.
    """
    kwargs['file'] = getattr(local_context, 'output', sys.stdout)
    try:
        print(text, *args, **kwargs)
    except UnicodeEncodeError:
        text = text.encode(io_encoding, 'replace').decode(io_encoding)
        print(text, *args, **kwargs)
    kwargs['file'].flush()  # flush to make sure the output is printed right away
```
Note that the print call raising the exception we see is the second one, not the first. This is because the code assumes that `io_encoding` and `sys.stdout.encoding` are the same.

In Python 2, when output is piped/redirected, this assumption does not hold since `sys.stdout.encoding` is `None`, while `io_encoding` will be the first non-`None` value of `sys.stdout.encoding`, `locale.getpreferredencoding()` and `'utf8'` ([flexget/utils/tools.py](https://github.com/Flexget/Flexget/blob/develop/flexget/utils/tools.py#L221):221):

```python
# Determine the encoding for io
io_encoding = None
if hasattr(sys.stdout, 'encoding'):
    io_encoding = sys.stdout.encoding
if not io_encoding:
    try:
        io_encoding = locale.getpreferredencoding()
    except Exception:
        pass
if not io_encoding:
    # Default to utf8 if nothing can be determined
    io_encoding = 'utf8'
else:
    # Normalize the encoding
    io_encoding = io_encoding.lower()
    if io_encoding == 'cp65001':
        io_encoding = 'utf8'
    elif io_encoding in ['us-ascii', '646', 'ansi_x3.4-1968']:
        io_encoding = 'ascii'
```

This means that when the fallback does encoding to replace unicode characters, it's encoding both from and to utf-8, so no characters are replaced.

The fix is to modify `console` to either encode/decode from/to `sys.stdout.encoding` with a fallback to utf-8, or you could make a solution similar to 13e2857.

Alternatively you could overwrite `sys.stdout` in a single place (using something like the code I posted [here](https://github.com/beautify-web/js-beautify/issues/1099#issuecomment-274080899) and remove the corresponding code from any other functions that write directly to stdout.

**Comment by gazpachoking** [comment] 2017-01-27 19:33
@tobbez Good insight. I'll have a play and see what I can come up with.

**Comment by gazpachoking** [comment] 2017-01-27 20:32
Okay, I have something to test over in that [PR branch](1659). I'm testing on windows, so I'm not actually sure it fixes the piping issue. If someone wants to test that branch and confirm over there it would be nice.

**Comment by mourningsun75** [comment] 2017-06-17 09:24
Nothing new here?
With the current version the error still occurs

**Comment by tobbez** [comment] 2017-06-17 16:00
The linked PR fixes the issue, but I assume the TODOs listed in it need to be fixed before it can be merged.

**Comment by tobbez** [comment] 2021-05-05 08:12
This issue does not occur on Python 3.

As Python 2 is EOL, this issue and the related PR #1659 can both be closed.

**Comment by gazpachoking** [comment] 2021-05-05 13:15
🥳

**Closed by gazpachoking** 2021-05-05 13:15 UTC
Labels: Bug, CLI
