### ISSUE TITLE
imdb_watchlist user_id variable size needs increased

### ISSUE THREAD

**Issue by paughbm** [Flexget/Flexget#2396] opened 2019-05-21 13:52 UTC
### Steps to reproduce:
- Step 1: ...

#### Config:
```
Paste FULL config and remove any personal info if config is too long, attach the file to the ticket.
If issue is with a single task, you can get get resulting configuration by running:
  flexget execute --task <NAME> --dump-config
Make sure to redact any personal information (passwords, api keys, etc) !
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
paste log output here
```
</details>

### Additional information:

- FlexGet version:
- Python version:
- Installation method:
- Using daemon (yes/no):
- OS and version:
- Link to crash log:

**Comment by gazpachoking** [comment] 2019-05-21 14:05
Duplicate of #2397

**Closed by gazpachoking** 2019-05-21 14:05 UTC
