### ISSUE TITLE
no urls found in cronjob, but urls found by doing manual

### ISSUE THREAD

**Issue by scrimpy** [Flexget/Flexget#945] opened 2016-03-11 17:27 UTC
why is this happening?

cron:
```
2016-03-11 18:00 INFO     pyload        themitdnb task  No suited urls in entry 2N
2016-03-11 18:00 INFO     pyload        themitdnb task  No suited urls in entry Gridlok
2016-03-11 18:00 INFO     pyload        themitdnb task  No suited urls in entry 
MOUNT
```

manual, after deleting db-config.sqlite because seen plugin says its already made its way to pyload:
```
2016-03-11 18:18 VERBOSE  manipulate    themitdnb task  Field `title` is now `2N`
2016-03-11 18:18 VERBOSE  manipulate    themitdnb task  Field `title` is now `Gridlok`
2016-03-11 18:18 VERBOSE  manipulate    themitdnb task  Field `title` is now `Gridlok`
2016-03-11 18:18 VERBOSE  manipulate    themitdnb task  Field `title` is now `Gridlok`
2016-03-11 18:18 VERBOSE  manipulate    themitdnb task  Field `title` is now `MOUNT`
2016-03-11 18:18 VERBOSE  manipulate    themitdnb task  Field `title` is now `MOUNT`
2016-03-11 18:18 VERBOSE  manipulate    themitdnb task  Modified 6 entries.
2016-03-11 18:18 VERBOSE  task          themitdnb task  ACCEPTED: `2N` by accept_all plugin
2016-03-11 18:18 VERBOSE  task          themitdnb task  ACCEPTED: `Gridlok` by accept_all plugin
2016-03-11 18:18 VERBOSE  task          themitdnb task  ACCEPTED: `MOUNT` by accept_all plugin
2016-03-11 18:18 VERBOSE  details       themitdnb task  Summary - Accepted: 6 (Rejected: 0 Undecided: 0 Failed: 0)
```

```
  themitdnb task:
    rss:
      url: 
      link: link
    cookies:
      file: /root/.mozilla/firefox/gagl46zl.default/cookies.sqlite
    manipulate:

      package: '{{title}}'
      queue: yes
      parse_url: yes
      hoster:
       - UploadedTo
      multiple_hoster: yes
      enabled: yes
```

**Comment by scrimpy** [comment] 2016-03-12 08:31
i really dont get why flexget marks as seen, when pyload rejects it. 
on the next run the package gets rejected, because its seen, but its not in pyload.
tho the bug isnt related to the cronjob, sometimes it works, sometimes not.

**Comment by cvium** [comment] 2016-03-12 08:44
`seen` doesn't really know what pyload is doing... Stuff is marked as `seen` when they are accepted, so if nothing is rejecting or failing the entries (pyload in this instance), then it's working as intended.

**Comment by scrimpy** [comment] 2016-03-12 09:40
running an cronjob with loglevel debug now. this might show something

**Comment by scrimpy** [comment] 2016-03-12 17:41
okay, this is not a flexget bug, its a pyload feature once again.

all the parse magic is done by this:

urlmatcher = re.compile(r"((https?|ftps?|xdcc|sftp):((//)|(\\\\))+[\w\d:#@%/;$()~_?\+\-=\\\.&]*)", re.IGNORECASE)
        if url:
            page = getURL(url)
            urls += [x[0] for x in urlmatcher.findall(page)]

its simply not working reliable, if you need a cookie to open the website.

is there a chance to add an parser code to flexget, that searches the rss urls of the website for links inside the same cookie session, and just sends the hoster links to pyload?

**Closed** 2016-03-13 06:56 UTC

**Comment by cvium** [comment] 2016-03-13 07:09
> is there a chance to add an parser code to flexget, that searches the rss urls of the website for links inside the same cookie session, and just sends the hoster links to pyload?

It should be within the realm of possibilities. You can attempt it yourself or hope someone in @Flexget/pyload is willing to look at it.
