### ISSUE TITLE
bug torrent_alive announce

### ISSUE THREAD

**Issue by dimakan** [Flexget/Flexget#1888] opened 2017-06-28 09:18 UTC
I upgraded again today and tested on 2.10.66
The issue still exists

> 2017-06-24 07:46 VERBOSE  details       get_tv          Summary - Accepted: 7 (Rejected: 4 Undecided: 2766 Failed: 0)
> 2017-06-24 07:46 CRITICAL task          get_tv          BUG: Unhandled error in plugin torrent_alive: u'announce'
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
>     return method(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
>     return self.func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/torrent_alive.py", line 243, in on_task_output
>     tracker = torrent.content['announce']
> KeyError: u'announce'

**Comment by cvium** [comment] 2017-06-28 09:23
No one is going to touch this until the issue template is filled with all info.

**Comment by dimakan** [comment] 2017-06-28 16:21
Sorry. First time...
Will update soon

**Comment by zilexa** [comment] 2017-07-09 21:08
Duplicate, proper bug report: https://github.com/Flexget/Flexget/issues/1891

**Comment by cvium** [comment] 2017-07-10 06:15
Actually, #1891 is a duplicate of this. Normally we'd close yours, but since this one hasn't been updated in a while...

**Closed by cvium** 2017-07-10 06:15 UTC
Labels: Pending Issue Template
