### ISSUE TITLE
api_tvmaze sqlite3.IntegrityError 

### ISSUE THREAD

**Issue by fabrizio5680** [Flexget/Flexget#868] opened 2016-02-17 14:01 UTC
1.2.454 on Python 2.7.11 running on Android.

```
2016-02-17 13:56 DEBUG    api_tvmaze    tvshows         creating new episode for show Modern Family
2016-02-17 13:56 CRITICAL task          tvshows         BUG: Unhandled error in plugin discover: (sqlite3.IntegrityError) UNIQUE constraint failed: tvmaze_episode.tvmaze_id [SQL: u'INSERT INTO tvmaze_episode (tvmaze_id, series_id, number, season_number, title, airdate, url, original_image, medium_image, airstamp, runtime, summary, last_update) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (574774, 80, 13, 7, u'Thunk in the Trunk', '2016-02-17 00:00:00.000000', u'http://www.tvmaze.com/episodes/574774/modern-family-7x13-thunk-in-the-trunk', None, None, '2016-02-17 21:00:00.000000', 30, u"Now that Claire has been running the closet business for a while, she \nand Phil have fallen into a new rhythm, with Claire assuming the role of \nthe wheeling and dealing breadwinner and Phil as the invisible \nhousewife, but Phil will not stand for being ignored and \nunderappreciated for long. Meanwhile, Jay lets his jealousy get the best\n of him when a life-size cutout of Gloria for her grocery store hot \nsauce display solicits all kinds of unsavory attention from men, so he \nenlists Manny as his accomplice in a poorly orchestrated heist. And, Cam\n and Mitch are being extra hospitable to get better reviews for their \nrental property, but when the new renters start acting undeniably \nsuspicious, they can't help but snoop.", '2016-02-17 13:56:24.786713')]
2016-02-17 13:56 CRITICAL manager       tvshows         An unexpected crash has occurred. Writing crash report to /storage/external/mxq/.flexget/crash_report.2016.02.17.135624834568.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.454
2016-02-17 13:56 DEBUG    manager       tvshows         Traceback:
Traceback (most recent call last):
  File "/opt/lib/python2.7/site-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/opt/lib/python2.7/site-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/opt/lib/python2.7/site-packages/flexget/plugins/input/discover.py", line 268, in on_task_input
    entries = self.estimated(entries)
  File "/opt/lib/python2.7/site-packages/flexget/plugins/input/discover.py", line 190, in estimated
    est_date = estimator.estimate(entry)
  File "/opt/lib/python2.7/site-packages/flexget/plugins/estimators/est_released.py", line 28, in estimate
    estimate = estimator(entry)
  File "/opt/lib/python2.7/site-packages/flexget/plugins/estimators/est_release_series_tvmaze.py", line 51, in estimate
    episode = lookup(**kwargs)
  File "/opt/lib/python2.7/site-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/opt/lib/python2.7/site-packages/flexget/utils/sqlalchemy_utils.py", line 137, in __exit__
    self.commit()
  File "/opt/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/opt/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/opt/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/opt/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/opt/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/opt/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/opt/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/opt/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/opt/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)
  File "/opt/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/opt/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/opt/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/opt/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/opt/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: tvmaze_episode.tvmaze_id [SQL: u'INSERT INTO tvmaze_episode (tvmaze_id, series_id, number, season_number, title, airdate, url, original_image, medium_image, airstamp, runtime, summary, last_update) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (574774, 80, 13, 7, u'Thunk in the Trunk', '2016-02-17 00:00:00.000000', u'http://www.tvmaze.com/episodes/574774/modern-family-7x13-thunk-in-the-trunk', None, None, '2016-02-17 21:00:00.000000', 30, u"Now that Claire has been running the closet business for a while, she \nand Phil have fallen into a new rhythm, with Claire assuming the role of \nthe wheeling and dealing breadwinner and Phil as the invisible \nhousewife, but Phil will not stand for being ignored and \nunderappreciated for long. Meanwhile, Jay lets his jealousy get the best\n of him when a life-size cutout of Gloria for her grocery store hot \nsauce display solicits all kinds of unsavory attention from men, so he \nenlists Manny as his accomplice in a poorly orchestrated heist. And, Cam\n and Mitch are being extra hospitable to get better reviews for their \nrental property, but when the new renters start acting undeniably \nsuspicious, they can't help but snoop.", '2016-02-17 13:56:24.786713')]
2016-02-17 13:56 WARNING  task          tvshows         Aborting task (plugin: discover)
```

Also Attached log
[log.txt](https://github.com/Flexget/Flexget/files/134434/log.txt)

**Comment by liiight** [comment] 2016-02-18 13:22
This is very weird. is this consistent? If so, can you run this task in debug please?

**Comment by scottwallacesh** [comment] 2016-02-20 15:33
I'm seeing this too.  I managed to workaround it by deleting everything in the `tvmaze_episode` table.

i.e. `delete from tvmaze_episode;`

**Comment by liiight** [comment] 2016-02-20 15:50
This will be near impossible to figure out without debug logs... What show you got this on?

**Comment by scottwallacesh** [comment] 2016-02-20 15:55
Can you explain how to enable debug? I've added `--debug-warnings` but it
doesn't result in any extra output in the log.

-- 
Scott. (mobile)

**Comment by scottwallacesh** [comment] 2016-02-20 16:05
Can you explain how to enable debug? I've added `--debug-warnings` but it doesn't result in any extra output in the log

**Comment by gazpachoking** [comment] 2016-02-20 16:32
@liiight I think the problem is here: https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/api_tvmaze.py#L516-L517

The episode id is a unique column in the table, but if those second 2 filters don't match, it'll try to create another row with the same episode id.

**Comment by gazpachoking** [comment] 2016-02-20 20:07
Maybe data changed at tvmaze since cache? That traceback seems to show it is happening somehow.

**Comment by fmoledina** [comment] 2016-03-02 05:01
Hello, I am having the same issue using Flexget 1.2.460 on Ubuntu 16.04, with the exact Modern Family S07E13 episode as the OP. My debug log is as follows:

    2016-03-01 21:55 INFO     webui                         Not starting webui as it's disabled or not set in the config
    2016-03-01 21:55 INFO     scheduler                     No schedules defined in config. Defaulting to run all tasks on a 1 hour interval.
    2016-03-01 21:55 INFO     scheduler                     Starting scheduler
    2016-03-01 21:55 VERBOSE  filesystem    tv-task         Starting to scan folders.
    2016-03-01 21:55 VERBOSE  filesystem    tv-task         Scanning folder /media/share/Shared/Media/TV/. Recursion is set to False.
    
    <snip>
    
    2016-03-01 21:55 VERBOSE  discover      tv-task         Discovering 24 titles ...
    2016-03-01 21:55 INFO     discover      tv-task         Ignoring interval because of --discover-now
    2016-03-01 21:56 INFO     task          tv-task         Plugin discover has requested task to be ran again after execution has completed.
    2016-03-01 21:56 CRITICAL task          tv-task         BUG: Unhandled error in plugin discover: (sqlite3.IntegrityError) UNIQUE constraint failed: tvmaze_episode.tvmaze_id [SQL: u'INSERT INTO tvmaze_episode (tvmaze_id, series_id, number, season_number, title, airdate, url, original_image, medium_image, airstamp, runtime, summary, last_update) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (574774, 80, 13, 7, u'Thunk in the Trunk', '2016-02-17 00:00:00.000000', u'http://www.tvmaze.com/episodes/574774/modern-family-7x13-thunk-in-the-trunk', u'http://tvmazecdn.com/uploads/images/original_untouched/45/113134.jpg', u'http://tvmazecdn.com/uploads/images/medium_landscape/45/113134.jpg', '2016-02-17 21:00:00.000000', 30, u"Now that Claire has been running the closet business for a while, she \nand Phil have fallen into a new rhythm, with Claire assuming the role of \nthe wheeling and dealing breadwinner and Phil as the invisible \nhousewife, but Phil will not stand for being ignored and \nunderappreciated for long. Meanwhile, Jay lets his jealousy get the best\n of him when a life-size cutout of Gloria for her grocery store hot \nsauce display solicits all kinds of unsavory attention from men, so he \nenlists Manny as his accomplice in a poorly orchestrated heist. And, Cam\n and Mitch are being extra hospitable to get better reviews for their \nrental property, but when the new renters start acting undeniably \nsuspicious, they can't help but snoop.", '2016-03-01 21:56:06.566792')]
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
        return method(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
        return self.func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 274, in on_task_input
        entries = self.estimated(entries, estimation_mode)
      File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 190, in estimated
        est_date = estimator.estimate(entry)
      File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_released.py", line 28, in estimate
        estimate = estimator(entry)
      File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_release_series_tvmaze.py", line 51, in estimate
        episode = lookup(**kwargs)
      File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/flexget/utils/sqlalchemy_utils.py", line 137, in __exit__
        self.commit()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 801, in commit
        self.transaction.commit()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 392, in commit
        self._prepare_impl()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
        self.session.flush()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2019, in flush
        self._flush(objects)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2137, in _flush
        transaction.rollback(_capture_exception=True)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
        compat.reraise(exc_type, exc_value, exc_tb)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2101, in _flush
        flush_context.execute()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
        rec.execute(self)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
        uow
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
        mapper, table, insert)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 767, in _emit_insert_statements
        execute(statement, multiparams)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
        return meth(self, multiparams, params)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
        context)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
        exc_info
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
        context)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
        cursor.execute(statement, parameters)
    IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: tvmaze_episode.tvmaze_id [SQL: u'INSERT INTO tvmaze_episode (tvmaze_id, series_id, number, season_number, title, airdate, url, original_image, medium_image, airstamp, runtime, summary, last_update) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (574774, 80, 13, 7, u'Thunk in the Trunk', '2016-02-17 00:00:00.000000', u'http://www.tvmaze.com/episodes/574774/modern-family-7x13-thunk-in-the-trunk', u'http://tvmazecdn.com/uploads/images/original_untouched/45/113134.jpg', u'http://tvmazecdn.com/uploads/images/medium_landscape/45/113134.jpg', '2016-02-17 21:00:00.000000', 30, u"Now that Claire has been running the closet business for a while, she \nand Phil have fallen into a new rhythm, with Claire assuming the role of \nthe wheeling and dealing breadwinner and Phil as the invisible \nhousewife, but Phil will not stand for being ignored and \nunderappreciated for long. Meanwhile, Jay lets his jealousy get the best\n of him when a life-size cutout of Gloria for her grocery store hot \nsauce display solicits all kinds of unsavory attention from men, so he \nenlists Manny as his accomplice in a poorly orchestrated heist. And, Cam\n and Mitch are being extra hospitable to get better reviews for their \nrental property, but when the new renters start acting undeniably \nsuspicious, they can't help but snoop.", '2016-03-01 21:56:06.566792')]

Is there any traction on a fix? Also, how do I use the `delete from tvmaze_episode` workaround? Thanks.

**Comment by liiight** [comment] 2016-03-02 07:17
If it's the same episode it definitely happened at tvmaze. I guess I can handle this scenario, not sure if it's the correct approach since this is super rare

**Comment by henriksjodahl** [comment] 2016-03-04 12:14
I am having that same error on the same show and episode as well

**Comment by bird99** [comment] 2016-03-07 01:10
I had the same error but I think it's because I tried to do an upgrade without administrator access (Windows 10). The upgrade looked like it worked fine but I saw the same errors that people posted about.

**To fix the error I reinstalled FlexGet**

Steps Open command prompt (as administrator)
- Run: pip uninstall flexget,
-Then Run: pip install flexget

**Comment by fmoledina** [comment] 2016-03-07 01:28
@bird99, you're saying that by uninstalling and reinstalling Flexget, you've been able to successfully download Modern Family S07E13 without an error? I'm not sure how that would solve the issue. It doesn't work for me. I still get the error on Flexget 1.2.473.

**Comment by bird99** [comment] 2016-03-07 01:47
Sorry, you know what my error was NOT around any particular episode I was seeing errors from not having tvmaze properly installed

**Comment by liiight** [comment] 2016-03-07 06:59
Wait, does this error stop you from downloading that episode? Or breaks any other functionality?

**Comment by henriksjodahl** [comment] 2016-03-07 07:15
For me, it stops me from downloading this episode and all that follows for the show.

**Comment by liiight** [comment] 2016-03-07 07:20
I'll push some sort of fix for this ASAP, didn't realize the symptoms are that.

**Comment by henriksjodahl** [comment] 2016-03-07 07:26
Yeah, i guess that weren't that clear in any of the comments above

**Comment by liiight** [comment] 2016-03-07 08:49
If anyone feel like testing this from dev branch it'll be appreciated

**Closed** 2016-03-07 08:48 UTC
Labels: Bug

**Comment by fmoledina** [comment] 2016-03-07 13:53
Works for me, thanks. I cloned the dev branch, stopped my Flexget daemon, and used the flexget_vanilla.py to execute my tv-task with the --discover-now option. I've now got E13, 14 and 15 downloading. Thanks.

**Comment by liiight** [comment] 2016-03-07 14:24
:thumbsup:

**Comment by carda21** [comment] 2018-02-11 08:24
I seem to behaving this error now.....

[crash_report.2018.02.11.190628370968.log](https://github.com/Flexget/Flexget/files/1714180/crash_report.2018.02.11.190628370968.log)

**Comment by liiight** [comment] 2018-02-11 08:34
@carda21 please open a new issue and include debug logs
