### ISSUE TITLE
metainfo_series crash with guessit parsers

### ISSUE THREAD

**Issue by crawln45** [Flexget/Flexget#1098] opened 2016-04-27 05:14 UTC
Seems if normalize a name from Guessit parser as we do [here](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/metainfo/series.py#L47) It turns the valid = True to valid = False in the parsed results. Do we need to normalize the name?

@liiight @gazpachoking @stevezau 

```
2016-04-27 00:17 DEBUG    manager       test            Traceback:
Traceback (most recent call last):
  File "/home/crawln/git/Flexget/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/home/crawln/git/Flexget/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/crawln/git/Flexget/flexget/plugins/metainfo/series.py", line 33, in on_task_metainfo
    self.guess_entry(entry)
  File "/home/crawln/git/Flexget/flexget/plugins/metainfo/series.py", line 48, in guess_entry
    populate_entry_fields(entry, parsed, config)
  File "/home/crawln/git/Flexget/flexget/plugins/filter/series.py", line 870, in populate_entry_fields
    entry['series_id'] = parser.pack_identifier
  File "/home/crawln/git/Flexget/flexget/plugins/parsers/parser_common.py", line 551, in pack_identifier
    return self.identifier
  File "/home/crawln/git/Flexget/flexget/plugins/parsers/parser_common.py", line 542, in identifier
    return self.identifiers[0]
  File "/home/crawln/git/Flexget/flexget/plugins/parsers/parser_common.py", line 527, in identifiers
    raise Exception('Series flagged invalid')
Exception: Series flagged invalid
```

**Comment by crawln45** [comment] 2016-04-27 05:31
@Toilal pretty much the same as #888 but test config can be used to reproduce

```
tasks:
  test:
    mock:
      - title: Blindspot.S01E19.In.the.Comet.of.Us
        url: Blindspot.S01E19.In.the.Comet.of.Us.mkv
    metainfo_series: yes
    parsing:
      series: guessit
    exec:
      - exec "Trakt Name {{series_name}}"
```

**Comment by cvium** [comment] 2016-08-08 13:05
Seems like a duplicate of #735

**Closed by cvium** 2016-08-08 13:05 UTC
