### ISSUE TITLE
Subliminal plugin unusable

### ISSUE THREAD

**Issue by lepinkainen** [Flexget/Flexget#822] opened 2016-01-26 09:20 UTC
Subliminal has a requirement of ```guessit<2.0,>=0.9.1```, Flexget requires ```guessit>=2.0rc5```

It's tedious to get both working at the same time, since installing subliminal will uninstall the later version of guessit required by flesxget.

**Comment by cvium** [comment] 2016-01-26 09:22
Duplicate of #803

**Closed by cvium** 2016-01-26 09:22 UTC
Labels: Bug
