### ISSUE TITLE
Unhandled error ConnectionError in imdb_watchlist

### ISSUE THREAD

**Issue by lepinkainen** [Flexget/Flexget#810] opened 2016-01-21 07:56 UTC
```
2016-01-16 12:15 VERBOSE  imdb_list     imdb_watchlist  Retrieving imdb list: watchlist
2016-01-16 12:15 WARNING  requests.packages.urllib3.connectionpool                 Retrying (Retry(total=0, connect=None, read=None, redirect=0)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x36efd6d0b10>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /user/ur1250180/watchlist?view=compact
2016-01-16 12:15 CRITICAL task          imdb_watchlist  BUG: Unhandled error in plugin imdb_list: HTTPConnectionPool(host='www.imdb.com', port=80): Max retries exceeded with url: /user/ur1250180/watchlist?view=compact (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x36eed6ec410>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/cached_input.py", line 140, in wrapped_func
    response = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/imdb_list.py", line 62, in on_task_input
    page = task.requests.get(url, params=params, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/requests.py", line 153, in request
    result = requests.Session.request(self, method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='www.imdb.com', port=80): Max retries exceeded with url: /user/ur1250180/watchlist?view=compact (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x36eed6ec410>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by crawln45** [comment] 2016-01-21 08:05
This is basically a duplicate of #807

**Comment by liiight** [comment] 2016-01-21 08:35
Yep.

**Closed by liiight** 2016-01-21 08:35 UTC
Labels: Bug
